server.port=8080

# Oracle Autonomous Database
# Se agregó el parámetro TNS_ADMIN apuntando a la nueva carpeta de Andrés
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=adb.sa-bogota-1.oraclecloud.com)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=gf0f40512fad804_gestionbd_low.adb.oraclecloud.com))(SECURITY=(SSL_SERVER_DN_MATCH=yes)(MY_WALLET_DIRECTORY=/home/andres/oracle_wallets/GestionBD_Andres)))
spring.datasource.username=tecnologoserviciodepolicia@gmail.com
spring.datasource.password=Ananrollona2021*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# CORS
cors.allowed-origins=https://mpetracksystem.trabajosucc.site
